services:
  mysql:
    image: mysql:8.0
    container_name: NewMarro_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: newmarro
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports: 
      - "3308:3306"
    volumes: 
      - newmarro_mysql_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: NewMarro_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8082:80"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newmarro_php
    restart: always
    volumes: 
      - .:/var/www/html
    ports:
      - "8000:80"

volumes:
  newmarro_mysql_data:
