services:
  mysql:
    image: mysql:8.0
    container_name: Marro_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: marro
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports: 
      - "3307:3306"
    volumes: 
      - mysql_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: Marro_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marro_php
    restart: always
    volumes: 
      - .:/var/www/html
    ports:
      - "80:80"

volumes:
  mysql_data:
